#!/bin/sh

#HERE=`dirname $0`

export TPTP=.
#export LEO3=$HERE/leo3.jar
#export EPROVER=$HERE/externals/eprover
#export CVC4=$HERE/externals/cvc4

python3 ../ltb.py batch3 Output~ --tempdir Tmp~ --logdir Log~ --clearoutputdir --withProfile